version: '3'

services:
  influxdb:
    image: influxdb:2.7
    container_name: coinlizard-influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=password123
      - DOCKER_INFLUXDB_INIT_ORG=coinlizard
      - DOCKER_INFLUXDB_INIT_BUCKET=coinlizard
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-token

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: coinlizard-api
    ports:
      - "3000:3000"
    environment:
      - RUST_LOG=debug
      - INFLUXDB_URL=http://influxdb:8086
      - INFLUXDB_TOKEN=my-super-secret-token
      - INFLUXDB_ORG=coinlizard
      - INFLUXDB_BUCKET=coinlizard
    depends_on:
      - influxdb
    restart: on-failure

volumes:
  influxdb-data: 